In [8]:
import re
tmp1 = input()
tmp_row = re.match('^\[\d+', tmp1).group(0)
print(tmp_row)

[3,4]
[3


In [27]:
import numpy as np
matrix = np.arange(3**2).reshape((3,3)) * 0
matrix[1,2] = 2
matrix[1,1] = 3
print(matrix)
tmp = np.where(matrix == 0)[0][5]
print(tmp)

[[0 0 0]
 [0 3 2]
 [0 0 0]]
2
